
import numpy as np

class MHDEngine:
    """
    Represents the core physics model of a Magnetohydrodynamic (MHD) engine.
    This model calculates the Lorentz force generated by the interaction of a
    magnetic field and a plasma (ionized gas).
    """
    def __init__(self, magnetic_field_strength, plasma_velocity, plasma_charge_density):
        """
        Initializes the MHD Engine model.

        Args:
            magnetic_field_strength (np.ndarray): A 3D vector representing the magnetic field (in Teslas).
            plasma_velocity (np.ndarray): A 3D vector representing the velocity of the plasma (in m/s).
            plasma_charge_density (float): The net charge density of the plasma (in Coulombs per cubic meter).
        """
        if not isinstance(magnetic_field_strength, np.ndarray) or not magnetic_field_strength.shape == (3,):
            raise ValueError("Magnetic field strength must be a 3D numpy array.")
        if not isinstance(plasma_velocity, np.ndarray) or not plasma_velocity.shape == (3,):
            raise ValueError("Plasma velocity must be a 3D numpy array.")

        self.magnetic_field = magnetic_field_strength
        self.plasma_velocity = plasma_velocity
        self.plasma_charge_density = plasma_charge_density

    def calculate_lorentz_force(self):
        """
        Calculates the Lorentz force vector.
        The formula is F = q * (v x B), where:
        - F is the force vector (in Newtons per cubic meter).
        - q is the plasma charge density.
        - v is the plasma velocity vector.
        - B is the magnetic field vector.

        Returns:
            np.ndarray: The resulting 3D force vector.
        """
        force_density = self.plasma_charge_density * np.cross(self.plasma_velocity, self.magnetic_field)
        return force_density

    def get_thrust(self, channel_volume):
        """
        Calculates the total thrust produced by the engine.

        Args:
            channel_volume (float): The volume of the plasma channel where the interaction occurs (in cubic meters).

        Returns:
            np.ndarray: The total thrust vector (in Newtons).
        """
        force_density = self.calculate_lorentz_force()
        total_thrust = force_density * channel_volume
        return total_thrust

if __name__ == '__main__':
    # --- Simulation Parameters ---
    # Toroidal magnetic field, primarily in the Z-direction for this segment
    B = np.array([0, 0, 5.0])  # 5.0 Tesla

    # Plasma injected radially outward from the core, primarily in the X-Y plane
    v = np.array([15000, 0, 0])  # 15,000 m/s

    # Charge density of the ionized gas (e.g., Argon plasma)
    q = 0.025  # Coulombs/m^3

    # Volume of the MHD channel where the force is applied
    channel_vol = 2.5 # m^3

    # --- Engine Simulation ---
    engine = MHDEngine(magnetic_field_strength=B, plasma_velocity=v, plasma_charge_density=q)
    force_per_volume = engine.calculate_lorentz_force()
    total_thrust_vector = engine.get_thrust(channel_volume=channel_vol)
    total_thrust_magnitude = np.linalg.norm(total_thrust_vector)

    print("--- Project Chimera: MHD Engine Simulation ---")
    print(f"Magnetic Field (B): {engine.magnetic_field} T")
    print(f"Plasma Velocity (v): {engine.plasma_velocity} m/s")
    print(f"Plasma Charge Density (q): {engine.plasma_charge_density} C/m^3")
    print("-" * 20)
    print(f"Calculated Lorentz Force Density (F): {force_per_volume} N/m^3")
    print(f"MHD Channel Volume: {channel_vol} m^3")
    print("-" * 20)
    print(f"Total Thrust Vector: {total_thrust_vector} N")
    print(f"Total Thrust Magnitude: {total_thrust_magnitude:.2f} N")

    # The direction of the force is perpendicular to both velocity and magnetic field,
    # resulting in vertical lift in this configuration (along the Y-axis).
